<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gossipinggirls"
    nsURI="http://www.eclipse.org/emf/henshin/examples/gossipinggirls" nsPrefix="gossip">
  <eClassifiers xsi:type="ecore:EClass" name="Girl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="secrets" upperBound="-1"
        eType="#//Secret"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Secret"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="girls" upperBound="-1"
        eType="#//Girl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secrets" upperBound="-1"
        eType="#//Secret" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
