/**
 * generated by Xtext
 */
package eu.artist.postmigration.nfrvt.lang.tsl.ui.quickfix;

import eu.artist.postmigration.nfrvt.lang.common.ui.quickfix.ARTISTCommonQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class TSLQuickfixProvider extends ARTISTCommonQuickfixProvider {
}
