/**
 * generated by Xtext
 */
package eu.artist.postmigration.nfrvt.lang.gel.scoping;

import eu.artist.postmigration.nfrvt.lang.common.scoping.ARTISTCommonScopeProvider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class GELScopeProvider extends ARTISTCommonScopeProvider {
  public IScope getScope(final EObject context, final EReference reference) {
    return super.getScope(context, reference);
  }
}
