/*
* generated by Xtext
*/
package eu.artist.postmigration.nfrvt.lang.nsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.artist.postmigration.nfrvt.lang.nsl.services.NSLGrammarAccess;

public class NSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private NSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.artist.postmigration.nfrvt.lang.nsl.parser.antlr.internal.InternalNSLParser createParser(XtextTokenStream stream) {
		return new eu.artist.postmigration.nfrvt.lang.nsl.parser.antlr.internal.InternalNSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ARTISTModel";
	}
	
	public NSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(NSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
