/*******************************************************************************
 * Copyright (c) 2014 Atos.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * 	Burak Karaboga (Atos) - main development
 * 	Initially developed in the context of ARTIST EU project www.artist-project.eu
 *******************************************************************************/
package eu.artist.tft

import java.util.Arrays;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;

import eu.artist.premigration.tft.tft.model.Component;
import eu.artist.premigration.tft.tft.model.MigrationGoals;
import eu.artist.premigration.tft.tft.model.TechnicalGoals;

import eu.artist.premigration.tft.tft.model.migrationstrategy.MigrationStrategyContainer;
import eu.artist.premigration.tft.tft.model.migrationstrategy.MigrationStrategy;
import eu.artist.premigration.tft.tft.model.migrationstrategy.Category;
import eu.artist.premigration.tft.tft.model.migrationstrategy.Complexity;

//declare any global variables here

global eu.artist.premigration.tft.tft.model.Component component;
global java.util.List suggestedStrategyIDs;
global java.util.Map strategiesByCategory;
global eu.artist.premigration.tft.tft.model.MigrationGoals migrationGoals;


rule "SelectAllAvailableStrategiesForComponent"

	when
		$migrationStrategy : MigrationStrategy( targetPlatforms.contains(migrationGoals.technicalGoals.iaas.selectedTargetPlatform) && component.hasStereotype(category.getPossibleStereotypes()))
	then
		if (!suggestedStrategyIDs.contains($migrationStrategy.getId())){
			List containedStrategies = (List) strategiesByCategory.get($migrationStrategy.getCategory());
			if (containedStrategies != null){
				containedStrategies.add($migrationStrategy);
			}
			else {
				containedStrategies = new ArrayList();
				containedStrategies.add($migrationStrategy);
				strategiesByCategory.put($migrationStrategy.getCategory(), containedStrategies);
			}
		}
end

