//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LL.EAAddin.IntegrationArchitect.Plugin.ResolveParents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LL.EAAddin.IntegrationArchitect.Plugin.ResolveParents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;ResolveParents.
        /// </summary>
        internal static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdeininger.
        /// </summary>
        internal static string PlugAuthor {
            get {
                return ResourceManager.GetString("PlugAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional functionality for Enterprise Architect.
        /// </summary>
        internal static string PlugFNCGroupDescription {
            get {
                return ResourceManager.GetString("PlugFNCGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {eabc0a14-8107-447d-835d-7898f3161db1}.
        /// </summary>
        internal static string PlugGuid {
            get {
                return ResourceManager.GetString("PlugGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {94d6718e-3ea5-4498-ae67-b979a6f2c1ee}.
        /// </summary>
        internal static string PlugHostGuid {
            get {
                return ResourceManager.GetString("PlugHostGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {94d6718e-3ea5-4498-ae67-b979a6f2c1ee}.
        /// </summary>
        internal static string PlugHostLicense {
            get {
                return ResourceManager.GetString("PlugHostLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {94d6718e-3ea5-4498-ae67-b979a6f2c1ee}.
        /// </summary>
        internal static string PluginFunctionGroupID {
            get {
                return ResourceManager.GetString("PluginFunctionGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {eabc0a14-8107-447d-835d-7898f3161db1}.
        /// </summary>
        internal static string PlugLicense {
            get {
                return ResourceManager.GetString("PlugLicense", resourceCulture);
            }
        }
    }
}
