/*******************************************************************************
 * Copyright (c) 2014 Vienna University of Technology.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Martin Fleck (Vienna University of Technology) - initial API and implementation
 *
 * Initially developed in the context of ARTIST EU project www.artist-project.eu
 *******************************************************************************/
/*
* generated by Xtext
*/
package eu.artist.postmigration.nfrvt.lang.tsl.ui.labeling;

import com.google.inject.Inject;

import eu.artist.postmigration.nfrvt.lang.common.artistCommon.ImportNamespace;
import eu.artist.postmigration.nfrvt.lang.common.artistCommon.ImportURI;
import eu.artist.postmigration.nfrvt.lang.common.artistCommon.ImportURIorNamespace;
import eu.artist.postmigration.nfrvt.lang.tsl.tsl.Pattern;
import eu.artist.postmigration.nfrvt.lang.tsl.tsl.PatternImpact;
import eu.artist.postmigration.nfrvt.lang.tsl.validation.TSLLabelRenderer;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
public class TSLLabelProvider extends org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider {

	private TSLLabelRenderer renderer = new TSLLabelRenderer();
	
	@Inject
	public TSLLabelProvider(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	String text(Pattern pattern) {
		return renderer.render(pattern);
	}

	String text(PatternImpact impact) {
		return renderer.render(impact);
	}
	
	String text(ImportNamespace importNamespace) {
		return renderer.render(importNamespace);
	}
	
	String text(ImportURI importURI) {
		return renderer.render(importURI);
	}
	
	String text(ImportURIorNamespace i) {
		return renderer.render(i);
	}
	
	// Labels and icons can be computed like this:
	
//	String text(Greeting ele) {
//		return "A greeting to " + ele.getName();
//	}
//
//	String image(Greeting ele) {
//		return "Greeting.gif";
//	}
}
