//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
   // String param= (String)session.getAttribute("rule3");
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_MD_1QfUhEeKQUIzBL7h9Mw,_iwxy0RlKEeOYd55vlpVPlwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Process Related Tasks_67595034_3fa31d79_Activity.jpeg"
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_MD_1QfUhEeKQUIzBL7h9MwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Migration Artefact Reuse and Evolution_CBAF9C98_797fc1f1_Activity.jpeg"		
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_IqT8oPUhEeKQUIzBL7h9MwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Migration_AEAFBB87_5c7fe0e0_Activity.jpeg";
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_IqT8oPUhEeKQUIzBL7h9Mw,_ejQR8fU5EeKQUIzBL7h9Mw,_V-Vj4RjCEeOB0MMwY_jmZwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Business Model Related Tasks_2EA77441_1300224_Activity.jpeg"
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_EjTrAfUhEeKQUIzBL7h9MwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Pre-Migration_7166B2C2_1f36d81b_Activity.jpeg"
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_IqT8oPUhEeKQUIzBL7h9Mw,_ejQR8fU5EeKQUIzBL7h9Mw,_loPXMRfhEeO3_oOLnXbqDAActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Process Related Tasks_A42ED558_76b7633b_Activity.jpeg"
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_IqT8oPUhEeKQUIzBL7h9Mw,_dO7AcfUyEeKQUIzBL7h9MwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Application Discovery and Understanding_DF767F23_acde4e57_Activity.jpeg"
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9MwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Artist Methodology_D5FC1605_d5fc1605_Activity.jpeg"
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_IqT8oPUhEeKQUIzBL7h9Mw,_ejQR8fU5EeKQUIzBL7h9MwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Modernization_6152D5B_d37cfc8f_Activity.jpeg"
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_J_HzcfUhEeKQUIzBL7h9MwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Post-Migration_348DD504_e25dfa5d_Activity.jpeg"
contentPage.processPage.imageFiles["_LtldcfR-EeKQUIzBL7h9Mw,_IqT8oPUhEeKQUIzBL7h9Mw,_8IU9kPUyEeKQUIzBL7h9MwActivity"]="./../../ARTIST Methodology/capabilitypatterns/resources/Target Environment Specification_627EB8C5_2fe687f9_Activity.jpeg"
contentPage.processPage.elementUrls["_hg08cPXgEeK5hM6umiquuA"] = ["Functional test cases for the migrated application and their verdict","ARTIST Methodology/capabilitypatterns/Functional test cases for the migrated application and their ver_52CE261C.html"];
contentPage.processPage.elementUrls["_CnC0gBjBEeOB0MMwY_jmZw"] = ["Accountability Process","ARTIST Methodology/capabilitypatterns/Accountability Process_608AA34A.html"];
contentPage.processPage.elementUrls["_OAyaYPXXEeK5hM6umiquuA"] = ["Business Analyst","ARTIST Methodology/capabilitypatterns/Business Analyst_5CEC356A.html"];
contentPage.processPage.elementUrls["_G2hVoPXjEeK5hM6umiquuA"] = ["The new version of the artefact in a consistent state","ARTIST Methodology/capabilitypatterns/The new version of the artefact in a consistent state_69AD7585.html"];
contentPage.processPage.elementUrls["__oQDAPXgEeK5hM6umiquuA"] = ["Real-life functional test cases and their verdict","ARTIST Methodology/capabilitypatterns/Real-life functional test cases and their verdict_615B71BA.html"];
contentPage.processPage.elementUrls["_JqXNoBi-EeOB0MMwY_jmZw"] = ["Current Helpdesk process","ARTIST Methodology/capabilitypatterns/Current Helpdesk process_32392453.html"];
contentPage.processPage.elementUrls["_BRmwgBlOEeOYd55vlpVPlw"] = ["Monitor Artefact Quality","ARTIST Methodology/capabilitypatterns/Monitor Artefact Quality_1FBCCA5C.html"];
contentPage.processPage.elementUrls["_qLt-EPXiEeK5hM6umiquuA"] = ["List of incosistencies (issues) to be resolved","ARTIST Methodology/capabilitypatterns/List of incosistencies issues to be resolved_14A8E3E9.html"];
contentPage.processPage.elementUrls["_guzjgPU5EeKQUIzBL7h9Mw"] = ["Express Migration Requirements","ARTIST Methodology/capabilitypatterns/Express Migration Requirements_26C71E0E.html"];
contentPage.processPage.elementUrls["_jxk9gPUkEeKQUIzBL7h9Mw"] = ["Business Feasibility","ARTIST Methodology/capabilitypatterns/Business Feasibility_E45352A2.html"];
contentPage.processPage.elementUrls["_icIWwBjBEeOB0MMwY_jmZw"] = ["Current organization chart","ARTIST Methodology/capabilitypatterns/Current organization chart_D9AFD6EA.html"];
contentPage.processPage.elementUrls["_9JksAPXeEeK5hM6umiquuA"] = ["Legacy Application PIMs","ARTIST Methodology/capabilitypatterns/Legacy Application PIMs_2C67260E.html"];
contentPage.processPage.elementUrls["_oa3UcPUyEeKQUIzBL7h9Mw"] = ["Discover low level models from legacy artefacts","ARTIST Methodology/capabilitypatterns/Discover low level models from legacy artefacts_E25FC8C.html"];
contentPage.processPage.elementUrls["_OZmtEBlEEeOYd55vlpVPlw"] = ["Software Analyst","ARTIST Methodology/capabilitypatterns/Software Analyst_525D9C8C.html"];
contentPage.processPage.elementUrls["_PGCEwBjBEeOB0MMwY_jmZw"] = ["(Cloud)Provider Management Process","ARTIST Methodology/capabilitypatterns/Cloud Provider Management Process_721FDD7B.html"];
contentPage.processPage.elementUrls["_bMHpYRbrEeOcBIah627ajg"] = ["HRM","ARTIST Methodology/capabilitypatterns/HRM_E660E8C0.html"];
contentPage.processPage.elementUrls["_0PilsPXdEeK5hM6umiquuA"] = ["Software Analyst","ARTIST Methodology/capabilitypatterns/Software Analyst_58FFBE45.html"];
contentPage.processPage.elementUrls["_XO3NEBjBEeOB0MMwY_jmZw"] = ["Current provider management process","ARTIST Methodology/capabilitypatterns/Current provider management process_67773E46.html"];
contentPage.processPage.elementUrls["_dZZJEPVIEeKQUIzBL7h9Mw"] = ["Resolve Inconsistencies","ARTIST Methodology/capabilitypatterns/Resolve Inconsistencies_60E3286B.html"];
contentPage.processPage.elementUrls["_rFeH8Bi9EeOB0MMwY_jmZw"] = ["SLA Management","ARTIST Methodology/capabilitypatterns/SLA Management_5980F30.html"];
contentPage.processPage.elementUrls["_qc0jIPVIEeKQUIzBL7h9Mw"] = ["Change Implementation","ARTIST Methodology/capabilitypatterns/Change Implementation_6E14D90D.html"];
contentPage.processPage.elementUrls["_-91TcPUkEeKQUIzBL7h9Mw"] = ["Evaluate Preconditions","ARTIST Methodology/capabilitypatterns/Evaluate Preconditions_E0D7A559.html"];
contentPage.processPage.elementUrls["_PoKkoRjFEeOB0MMwY_jmZw"] = ["Sales strategy (including marketing activities, deliverly, etc)","ARTIST Methodology/capabilitypatterns/Sales strategy including marketing activities, deliverly, etc_7BDBE75D.html"];
contentPage.processPage.elementUrls["_YCyN0BlEEeOYd55vlpVPlw"] = ["Price determination","ARTIST Methodology/capabilitypatterns/Price determination_A62CD56E.html"];
contentPage.processPage.elementUrls["_f9zNgBlNEeOYd55vlpVPlw"] = ["MDE Artefacts in the workspace or the project repository","ARTIST Methodology/capabilitypatterns/MDE Artefacts in the workspace or the project repository_48ADDFC8.html"];
contentPage.processPage.elementUrls["_TzcwgBlNEeOYd55vlpVPlw"] = ["Identify Reusable Artefacts","ARTIST Methodology/capabilitypatterns/Identify Reusable Artefacts_26DC7BBB.html"];
contentPage.processPage.elementUrls["_1_YTAPXaEeK5hM6umiquuA"] = ["Detailed methodology workflow for the particular application","ARTIST Methodology/capabilitypatterns/Detailed methodology workflow for the particular application_6854E29A.html"];
contentPage.processPage.elementUrls["_AwRwoBlEEeOYd55vlpVPlw"] = ["Definition of the new customer relationship","ARTIST Methodology/capabilitypatterns/Definition of the new customer relationship_9F3DD9CB.html"];
contentPage.processPage.elementUrls["_fJ79kPXgEeK5hM6umiquuA"] = ["Annotated PIMs","ARTIST Methodology/capabilitypatterns/Annotated PIMs_20153093.html"];
contentPage.processPage.elementUrls["_GT6WkBi7EeOB0MMwY_jmZw"] = ["Business Analyst","ARTIST Methodology/capabilitypatterns/Business Analyst_191DBA12.html"];
contentPage.processPage.elementUrls["_gNvSAPXiEeK5hM6umiquuA"] = ["Formal listing of the changes to be made to the artefact in terms of primitive and complex changes","ARTIST Methodology/capabilitypatterns/Formal listing of the changes to be made to the artefact in term_30E82B9D.html"];
contentPage.processPage.elementUrls["_k9tfgBi9EeOB0MMwY_jmZw"] = ["Incidence Management Process redefined","ARTIST Methodology/capabilitypatterns/Incidence Management Process redefined_7767052A.html"];
contentPage.processPage.elementUrls["_yW7icPXWEeK5hM6umiquuA"] = ["Migration effort","ARTIST Methodology/capabilitypatterns/Migration effort_8D732115.html"];
contentPage.processPage.elementUrls["_pIWO0PXdEeK5hM6umiquuA"] = ["Processed higher-level models","ARTIST Methodology/capabilitypatterns/Processed higher-level models_9A635BD6.html"];
contentPage.processPage.elementUrls["_EJSJwPXXEeK5hM6umiquuA"] = ["Business situation of the legacy app","ARTIST Methodology/capabilitypatterns/Business situation of the legacy app_B9D771EE.html"];
contentPage.processPage.elementUrls["_fNZigPU2EeKQUIzBL7h9Mw"] = ["Tagret Environment Model Population","ARTIST Methodology/capabilitypatterns/Tagret Environment Model Population_E57C9064.html"];
contentPage.processPage.elementUrls["_sQRYIPXUEeK5hM6umiquuA"] = ["Reusable artifacts from repository","ARTIST Methodology/capabilitypatterns/Reusable artifacts from repository_39EB4A2.html"];
contentPage.processPage.elementUrls["_LtldcfR-EeKQUIzBL7h9Mw"] = ["Artist Methodology","ARTIST Methodology/capabilitypatterns/Artist Methodology_D5FC1605.html"];
contentPage.processPage.elementUrls["_8IU9kPUyEeKQUIzBL7h9Mw"] = ["Target Environment Specification","ARTIST Methodology/capabilitypatterns/Target Environment Specification_627EB8C5.html"];
contentPage.processPage.elementUrls["_EjTrAfUhEeKQUIzBL7h9Mw"] = ["Pre-Migration","ARTIST Methodology/capabilitypatterns/Pre-Migration_7166B2C2.html"];
contentPage.processPage.elementUrls["_Q7HnkBlEEeOYd55vlpVPlw"] = ["Software Architect","ARTIST Methodology/capabilitypatterns/Software Architect_87C4CB80.html"];
contentPage.processPage.elementUrls["_LaGF4Bi-EeOB0MMwY_jmZw"] = ["SLA","ARTIST Methodology/capabilitypatterns/SLA_5903DA05.html"];
contentPage.processPage.elementUrls["_ejQR8fU5EeKQUIzBL7h9Mw"] = ["Modernization","ARTIST Methodology/capabilitypatterns/Modernization_6152D5B.html"];
contentPage.processPage.elementUrls["_Cjev8PXfEeK5hM6umiquuA"] = ["Annotated PIMs","ARTIST Methodology/capabilitypatterns/Annotated PIMs_6CADB697.html"];
contentPage.processPage.elementUrls["_MdD3YBjBEeOB0MMwY_jmZw"] = ["(Redefined) accountability process","ARTIST Methodology/capabilitypatterns/Redefined accountability process_B470F466.html"];
contentPage.processPage.elementUrls["_9eLYIvXgEeK5hM6umiquuA"] = ["Migrated Application PSMs","ARTIST Methodology/capabilitypatterns/Migrated Application PSMs_621F012E.html"];
contentPage.processPage.elementUrls["_3R58wPXYEeK5hM6umiquuA"] = ["Technical Manager","ARTIST Methodology/capabilitypatterns/Technical Manager_68216A55.html"];
contentPage.processPage.elementUrls["_law1oBjCEeOB0MMwY_jmZw"] = ["Business Analyst","ARTIST Methodology/capabilitypatterns/Business Analyst_A125777A.html"];
contentPage.processPage.elementUrls["_baangBjBEeOB0MMwY_jmZw"] = ["Roles alignment process","ARTIST Methodology/capabilitypatterns/Roles alignment process_FB3290DE.html"];
contentPage.processPage.elementUrls["_d3UxEPXeEeK5hM6umiquuA"] = ["Benchmarks Provider","ARTIST Methodology/capabilitypatterns/Benchmarks Provider_D1D27543.html"];
contentPage.processPage.elementUrls["_7sIBIPXfEeK5hM6umiquuA"] = ["Developer","ARTIST Methodology/capabilitypatterns/Developer_812A4F23.html"];
contentPage.processPage.elementUrls["_BJMZoBjFEeOB0MMwY_jmZw"] = ["Future value propositions","ARTIST Methodology/capabilitypatterns/Future value propositions_6AC585E3.html"];
contentPage.processPage.elementUrls["_wcQygPVHEeKQUIzBL7h9Mw"] = ["Verification of the non- functional requirements","ARTIST Methodology/capabilitypatterns/Verification of the non- functional requirements_2D4CAAB6.html"];
contentPage.processPage.elementUrls["_-UFCcPU9EeKQUIzBL7h9Mw"] = ["Verification of the behavioral equivalence with end user based tests","ARTIST Methodology/capabilitypatterns/Verification of the behavioral equivalence with end user based t_CADD6BD.html"];
contentPage.processPage.elementUrls["_pYRFsPXTEeK5hM6umiquuA"] = ["Initial and final situation of the app","ARTIST Methodology/capabilitypatterns/Initial and final situation of the app_77439E4F.html"];
contentPage.processPage.elementUrls["_iLphgPUkEeKQUIzBL7h9Mw"] = ["Technical Feasibility","ARTIST Methodology/capabilitypatterns/Technical Feasibility_7BF48821.html"];
contentPage.processPage.elementUrls["_o8JJYPXeEeK5hM6umiquuA"] = ["Benchmarking Results","ARTIST Methodology/capabilitypatterns/Benchmarking Results_4B622946.html"];
contentPage.processPage.elementUrls["_J6N3gPXgEeK5hM6umiquuA"] = ["Integrator","ARTIST Methodology/capabilitypatterns/Integrator_58C608A2.html"];
contentPage.processPage.elementUrls["_RxORQPU2EeKQUIzBL7h9Mw"] = [" Application Artefacts Performance and Usage Profiling","ARTIST Methodology/capabilitypatterns/Application Artefacts Performance and Usage Profiling_2155D60C.html"];
contentPage.processPage.elementUrls["_2lkC4PXSEeK5hM6umiquuA"] = ["Migration Goals","ARTIST Methodology/capabilitypatterns/Migration Goals_4E475E82.html"];
contentPage.processPage.elementUrls["_iwxy0RlKEeOYd55vlpVPlw"] = ["Process Related Tasks","ARTIST Methodology/capabilitypatterns/Process Related Tasks_67595034.html"];
contentPage.processPage.elementUrls["_guzjgfU5EeKQUIzBL7h9Mw"] = ["Select Cloud Target","ARTIST Methodology/capabilitypatterns/Select Cloud Target_15603224.html"];
contentPage.processPage.elementUrls["_geifcPUkEeKQUIzBL7h9Mw"] = ["Business Evaluation","ARTIST Methodology/capabilitypatterns/Business Evaluation_A6CFE3E5.html"];
contentPage.processPage.elementUrls["_hkPm4BlNEeOYd55vlpVPlw"] = ["A list of potentially reusable artefacts to be published to the ARTIST marketplace","ARTIST Methodology/capabilitypatterns/A list of potentially reusable artefacts to be published to the _899DE6D4.html"];
contentPage.processPage.elementUrls["_vfA1APUkEeKQUIzBL7h9Mw"] = ["Decide whether to migrate or not","ARTIST Methodology/capabilitypatterns/Decide whether to migrate or not_B44F04CC.html"];
contentPage.processPage.elementUrls["_HTV1ABlEEeOYd55vlpVPlw"] = ["Revenue analysis","ARTIST Methodology/capabilitypatterns/Revenue analysis_A3B660A5.html"];
contentPage.processPage.elementUrls["_5dmEEBi9EeOB0MMwY_jmZw"] = ["Redefined SLA Management process","ARTIST Methodology/capabilitypatterns/Redefined SLA Management process_411F65B3.html"];
contentPage.processPage.elementUrls["_kZ58APXYEeK5hM6umiquuA"] = ["Risk analysis","ARTIST Methodology/capabilitypatterns/Risk analysis_C364369B.html"];
contentPage.processPage.elementUrls["_fJ79kfXgEeK5hM6umiquuA"] = ["Existing legacy application test cases","ARTIST Methodology/capabilitypatterns/Existing legacy application test cases_EAE44A9.html"];
contentPage.processPage.elementUrls["_JDkt8PXhEeK5hM6umiquuA"] = ["Legacy Application","ARTIST Methodology/capabilitypatterns/Legacy Application_C1CE7704.html"];
contentPage.processPage.elementUrls["__YxugPXeEeK5hM6umiquuA"] = ["Metamodel","ARTIST Methodology/capabilitypatterns/Metamodel_6D6B7326.html"];
contentPage.processPage.elementUrls["_QWLnoPXbEeK5hM6umiquuA"] = ["New desired situation characteristics","ARTIST Methodology/capabilitypatterns/New desired situation characteristics_A06CA10C.html"];
contentPage.processPage.elementUrls["_fCWQMPXSEeK5hM6umiquuA"] = ["Software Analyst","ARTIST Methodology/capabilitypatterns/Software Analyst_F5DDA34E.html"];
contentPage.processPage.elementUrls["_feEowBlGEeOYd55vlpVPlw"] = ["Business Manager","ARTIST Methodology/capabilitypatterns/Business Manager_D58B8453.html"];
contentPage.processPage.elementUrls["_iplcoPXSEeK5hM6umiquuA"] = ["Technical information about the legacy app to be migrated","ARTIST Methodology/capabilitypatterns/Technical information about the legacy app to be migrated_51F37853.html"];
contentPage.processPage.elementUrls["_aQ9DoBlGEeOYd55vlpVPlw"] = ["Costs","ARTIST Methodology/capabilitypatterns/Costs_AD38284D.html"];
contentPage.processPage.elementUrls["_FFe10PXjEeK5hM6umiquuA"] = ["Complete set of requested changes in addition to the deduced changes in a formal way","ARTIST Methodology/capabilitypatterns/Complete set of requested changes in addition to the deduced cha_EAE9F57.html"];
contentPage.processPage.elementUrls["_2iw-0PXYEeK5hM6umiquuA"] = ["Business Manager","ARTIST Methodology/capabilitypatterns/Business Manager_604B18E7.html"];
contentPage.processPage.elementUrls["_249tQBlDEeOYd55vlpVPlw"] = ["Customer relationship","ARTIST Methodology/capabilitypatterns/Customer relationship_69EAB4A.html"];
contentPage.processPage.elementUrls["_ipLREBi9EeOB0MMwY_jmZw"] = ["Current Incidence Management Process","ARTIST Methodology/capabilitypatterns/Current Incidence Management Process_C13F2499.html"];
contentPage.processPage.elementUrls["_bDS0YPVIEeKQUIzBL7h9Mw"] = ["Detect Inconsistencies","ARTIST Methodology/capabilitypatterns/Detect Inconsistencies_615D7A50.html"];
contentPage.processPage.elementUrls["_Dm2cAPXgEeK5hM6umiquuA"] = ["Migrated application source code","ARTIST Methodology/capabilitypatterns/Migrated application source code_F317B8D1.html"];
contentPage.processPage.elementUrls["_GZ1OkBlOEeOYd55vlpVPlw"] = ["Quality Manager","ARTIST Methodology/capabilitypatterns/Quality Manager_CADB1F8F.html"];
contentPage.processPage.elementUrls["_OKOrMBi-EeOB0MMwY_jmZw"] = ["(Redefined) helpdesk process","ARTIST Methodology/capabilitypatterns/Redefined helpdesk process_A00685F7.html"];
contentPage.processPage.elementUrls["_Axz-APXfEeK5hM6umiquuA"] = ["UML profiles","ARTIST Methodology/capabilitypatterns/UML profiles_53D15740.html"];
contentPage.processPage.elementUrls["_kv59APXfEeK5hM6umiquuA"] = ["Selected Cloud Offering Model","ARTIST Methodology/capabilitypatterns/Selected Cloud Offering Model_81EDD7C5.html"];
contentPage.processPage.elementUrls["_Zz9TcPVIEeKQUIzBL7h9Mw"] = ["Capture Changes","ARTIST Methodology/capabilitypatterns/Capture Changes_E8AC3D42.html"];
contentPage.processPage.elementUrls["_qV7pMB-TEeOifYBBi7fk6Q"] = ["Artifact Engineer","ARTIST Methodology/capabilitypatterns/Artifact Engineer_60634914.html"];
contentPage.processPage.elementUrls["_sVwR0BjCEeOB0MMwY_jmZw"] = ["Market analysis","ARTIST Methodology/capabilitypatterns/Market analysis_E74AF988.html"];
contentPage.processPage.elementUrls["_lRX9QPXdEeK5hM6umiquuA"] = ["Software Architect","ARTIST Methodology/capabilitypatterns/Software Architect_8378A8AB.html"];
contentPage.processPage.elementUrls["_Wmd_EBi7EeOB0MMwY_jmZw"] = ["Development processes redefined","ARTIST Methodology/capabilitypatterns/Development processes redefined_9B29601B.html"];
contentPage.processPage.elementUrls["_sYIWUBlEEeOYd55vlpVPlw"] = ["Key Associations","ARTIST Methodology/capabilitypatterns/Key Associations_9AA1CF1E.html"];
contentPage.processPage.elementUrls["_cuMVIPU2EeKQUIzBL7h9Mw"] = ["Target Environment Benchmarking","ARTIST Methodology/capabilitypatterns/Target Environment Benchmarking_2D432366.html"];
contentPage.processPage.elementUrls["_lRiHkPXYEeK5hM6umiquuA"] = ["Time series metrics (simulation)","ARTIST Methodology/capabilitypatterns/Time series metrics simulation_C9705A4.html"];
contentPage.processPage.elementUrls["_tVSnEPUyEeKQUIzBL7h9Mw"] = ["Understand and Transform the discovered models","ARTIST Methodology/capabilitypatterns/Understand and Transform the discovered models_24F5ED33.html"];
contentPage.processPage.elementUrls["_q_btQPXSEeK5hM6umiquuA"] = ["High level recommendations","ARTIST Methodology/capabilitypatterns/High level recommendations_42DE9E33.html"];
contentPage.processPage.elementUrls["__jmU0BjEEeOB0MMwY_jmZw"] = ["Current value proposition","ARTIST Methodology/capabilitypatterns/Current value proposition_712F2D3F.html"];
contentPage.processPage.elementUrls["_TSOo4BlEEeOYd55vlpVPlw"] = ["Market study","ARTIST Methodology/capabilitypatterns/Market study_63D07F2A.html"];
contentPage.processPage.elementUrls["_KfjjwPXhEeK5hM6umiquuA"] = ["Migrated application","ARTIST Methodology/capabilitypatterns/Migrated application_6441CA7D.html"];
contentPage.processPage.elementUrls["_3P1yIPXWEeK5hM6umiquuA"] = ["Migration tasks","ARTIST Methodology/capabilitypatterns/Migration tasks_E2BD81C4.html"];
contentPage.processPage.elementUrls["_EBaN4PXcEeK5hM6umiquuA"] = ["Modeler","ARTIST Methodology/capabilitypatterns/Modeler_A0D268CA.html"];
contentPage.processPage.elementUrls["_5bG5YPXiEeK5hM6umiquuA"] = ["An additional list of changes to be captured","ARTIST Methodology/capabilitypatterns/An additional list of changes to be captured_B3BC497C.html"];
contentPage.processPage.elementUrls["_6R7-wBlEEeOYd55vlpVPlw"] = ["List of key possible partners","ARTIST Methodology/capabilitypatterns/List of key possible partners_48A08C7A.html"];
contentPage.processPage.elementUrls["_2Mh20PXdEeK5hM6umiquuA"] = ["Application Components","ARTIST Methodology/capabilitypatterns/Application Components_4DD628CA.html"];
contentPage.processPage.elementUrls["_WZbWchbrEeOcBIah627ajg"] = ["(Redefined) accountability process","ARTIST Methodology/capabilitypatterns/Redefined accountability process_CF7E7E91.html"];
contentPage.processPage.elementUrls["_KfjjwfXhEeK5hM6umiquuA"] = ["Migration Goals","ARTIST Methodology/capabilitypatterns/Migration Goals_52DADE93.html"];
contentPage.processPage.elementUrls["_7LlVUPXeEeK5hM6umiquuA"] = ["Modeler","ARTIST Methodology/capabilitypatterns/Modeler_2F4809C0.html"];
contentPage.processPage.elementUrls["_yBS6kPXfEeK5hM6umiquuA"] = ["M2M Transformations","ARTIST Methodology/capabilitypatterns/M2M Transformations_4A134138.html"];
contentPage.processPage.elementUrls["_loPXMRfhEeO3_oOLnXbqDA"] = ["Process Related Tasks","ARTIST Methodology/capabilitypatterns/Process Related Tasks_A42ED558.html"];
contentPage.processPage.elementUrls["__ZJbkPXWEeK5hM6umiquuA"] = ["Component model","ARTIST Methodology/capabilitypatterns/Component model_BF925B30.html"];
contentPage.processPage.elementUrls["_4iqBoBjEEeOB0MMwY_jmZw"] = ["Value proposition definition","ARTIST Methodology/capabilitypatterns/Value proposition definition_86E89CD3.html"];
contentPage.processPage.elementUrls["_FKc5kPXcEeK5hM6umiquuA"] = ["Software Analyst","ARTIST Methodology/capabilitypatterns/Software Analyst_8DB07A80.html"];
contentPage.processPage.elementUrls["_SpcI0Bi7EeOB0MMwY_jmZw"] = ["Current development processes and methodology","ARTIST Methodology/capabilitypatterns/Current development processes and methodology_F29F8CA2.html"];
contentPage.processPage.elementUrls["_Wc4IEPU2EeKQUIzBL7h9Mw"] = ["Application Artefact Classification","ARTIST Methodology/capabilitypatterns/Application Artefact Classification_D980B250.html"];
contentPage.processPage.elementUrls["_DfW0QPXdEeK5hM6umiquuA"] = ["Legacy artefacts from the various use cases","ARTIST Methodology/capabilitypatterns/Legacy artefacts from the various use cases_57E767BF.html"];
contentPage.processPage.elementUrls["_MjSWEPXhEeK5hM6umiquuA"] = ["Values for quality metrics in comparison with migration goals and their verdict","ARTIST Methodology/capabilitypatterns/Values for quality metrics in comparison with migration goals an_2C0367D5.html"];
contentPage.processPage.elementUrls["_zMFEAPUhEeKQUIzBL7h9Mw"] = ["Technical Evaluation","ARTIST Methodology/capabilitypatterns/Technical Evaluation_1D5C89DB.html"];
contentPage.processPage.elementUrls["_3HYOIPXgEeK5hM6umiquuA"] = ["Migrated application source code","ARTIST Methodology/capabilitypatterns/Migrated application source code_8F01EEFA.html"];
contentPage.processPage.elementUrls["_VqEcsBjFEeOB0MMwY_jmZw"] = ["Support processes redefined (incidence management, helpdesk, etc)","ARTIST Methodology/capabilitypatterns/Support processes redefined incidence management, helpdesk, etc_E8BBC643.html"];
contentPage.processPage.elementUrls["_9eLYIfXgEeK5hM6umiquuA"] = ["M2T code generation patterns (transformations)","ARTIST Methodology/capabilitypatterns/M2T code generation patterns transformations_5781211E.html"];
contentPage.processPage.elementUrls["_6XanEPXWEeK5hM6umiquuA"] = ["Migration tasks complexity","ARTIST Methodology/capabilitypatterns/Migration tasks complexity_60D4D3B2.html"];
contentPage.processPage.elementUrls["_f_2yEBlEEeOYd55vlpVPlw"] = ["Key Resources","ARTIST Methodology/capabilitypatterns/Key Resources_4965AD3A.html"];
contentPage.processPage.elementUrls["_q_VBQBlNEeOYd55vlpVPlw"] = ["Publish Reusable Artefacts","ARTIST Methodology/capabilitypatterns/Publish Reusable Artefacts_D3D92CB1.html"];
contentPage.processPage.elementUrls["_NzKDgPXWEeK5hM6umiquuA"] = ["Source Code","ARTIST Methodology/capabilitypatterns/Source Code_1F328006.html"];
contentPage.processPage.elementUrls["_Wj5mwPXeEeK5hM6umiquuA"] = ["Categorization of the application artefact to application type(s)","ARTIST Methodology/capabilitypatterns/Categorization of the application artefact to application type s_4BD5E4CA.html"];
contentPage.processPage.elementUrls["_g5Za8PXeEeK5hM6umiquuA"] = ["Metrics for each provider","ARTIST Methodology/capabilitypatterns/Metrics for each provider_8F077C13.html"];
contentPage.processPage.elementUrls["_IQH5sBi9EeOB0MMwY_jmZw"] = ["Current updating process","ARTIST Methodology/capabilitypatterns/Current updating process_D1644B53.html"];
contentPage.processPage.elementUrls["_TJk3oBlOEeOYd55vlpVPlw"] = ["Artefacts published in the marketplace","ARTIST Methodology/capabilitypatterns/Artefacts published in the marketplace_E465AA78.html"];
contentPage.processPage.elementUrls["_i3zy8PXfEeK5hM6umiquuA"] = ["Models for available Cloud offerings","ARTIST Methodology/capabilitypatterns/Models for available Cloud offerings_18F06688.html"];
contentPage.processPage.elementUrls["_FdoDQBjFEeOB0MMwY_jmZw"] = ["Determine the channels","ARTIST Methodology/capabilitypatterns/Determine the channels_DA26F1DF.html"];
contentPage.processPage.elementUrls["_bKDyMPXhEeK5hM6umiquuA"] = ["Certifier","ARTIST Methodology/capabilitypatterns/Certifier_912A794A.html"];
contentPage.processPage.elementUrls["_J_HzcfUhEeKQUIzBL7h9Mw"] = ["Post-Migration","ARTIST Methodology/capabilitypatterns/Post-Migration_348DD504.html"];
contentPage.processPage.elementUrls["_QqnZwBi9EeOB0MMwY_jmZw"] = ["Update process redefined","ARTIST Methodology/capabilitypatterns/Update process redefined_C69E4BE6.html"];
contentPage.processPage.elementUrls["_uTIcMPXeEeK5hM6umiquuA"] = ["Target Environment Model","ARTIST Methodology/capabilitypatterns/Target Environment Model_CA6A7F22.html"];
contentPage.processPage.elementUrls["_2R7tUBfhEeO3_oOLnXbqDA"] = ["Update Processes","ARTIST Methodology/capabilitypatterns/Update Processes_B654B072.html"];
contentPage.processPage.elementUrls["_dO7AcfUyEeKQUIzBL7h9Mw"] = ["Application Discovery and Understanding","ARTIST Methodology/capabilitypatterns/Application Discovery and Understanding_DF767F23.html"];
contentPage.processPage.elementUrls["_JbXA8BjBEeOB0MMwY_jmZw"] = ["Current accountability process","ARTIST Methodology/capabilitypatterns/Current accountability process_8D5CB82.html"];
contentPage.processPage.elementUrls["_17ZCkPUkEeKQUIzBL7h9Mw"] = ["Methodology Customization","ARTIST Methodology/capabilitypatterns/Methodology Customization_76E68D31.html"];
contentPage.processPage.elementUrls["_3gfZEPXdEeK5hM6umiquuA"] = ["Application Artefact Runtime Trace","ARTIST Methodology/capabilitypatterns/Application Artefact Runtime Trace_8F37F878.html"];
contentPage.processPage.elementUrls["_f4t-0BjBEeOB0MMwY_jmZw"] = ["HRM","ARTIST Methodology/capabilitypatterns/HRM_9BCED610.html"];
contentPage.processPage.elementUrls["_U6Vn8PXeEeK5hM6umiquuA"] = ["Elementary Applications Runtime Traces","ARTIST Methodology/capabilitypatterns/Elementary Applications Runtime Traces_F958EFB7.html"];
contentPage.processPage.elementUrls["_z4CZwPXfEeK5hM6umiquuA"] = ["Migrated application PSMs","ARTIST Methodology/capabilitypatterns/Migrated application PSMs_C8EA8171.html"];
contentPage.processPage.elementUrls["_Y3PKEPXYEeK5hM6umiquuA"] = ["Organization models","ARTIST Methodology/capabilitypatterns/Organization models_26AE169A.html"];
contentPage.processPage.elementUrls["_8hjh4BlNEeOYd55vlpVPlw"] = ["Artefacts are inserted in the publishing queue of the marketplace","ARTIST Methodology/capabilitypatterns/Artefacts are inserted in the publishing queue of the marketplac_ACDBE562.html"];
contentPage.processPage.elementUrls["_9pQMMBi9EeOB0MMwY_jmZw"] = ["Helpdesk Process","ARTIST Methodology/capabilitypatterns/Helpdesk Process_2E907ED7.html"];
contentPage.processPage.elementUrls["_6c9_APXiEeK5hM6umiquuA"] = ["Extended set of changes to move the artefact from one consistent state to another","ARTIST Methodology/capabilitypatterns/Extended set of changes to move the artefact from one consistent_EC48172C.html"];
contentPage.processPage.elementUrls["_guzjhPU5EeKQUIzBL7h9Mw"] = ["Generate Feature Deployment","ARTIST Methodology/capabilitypatterns/Generate Feature Deployment_EB59002D.html"];
contentPage.processPage.elementUrls["_qTZN8BjBEeOB0MMwY_jmZw"] = ["Renewed organization chart","ARTIST Methodology/capabilitypatterns/Renewed organization chart_17C27038.html"];
contentPage.processPage.elementUrls["_guzjg_U5EeKQUIzBL7h9Mw"] = ["Generate Feature Source Code","ARTIST Methodology/capabilitypatterns/Generate Feature Source Code_E0BB201D.html"];
contentPage.processPage.elementUrls["_hL69EPXYEeK5hM6umiquuA"] = ["Economic metrics","ARTIST Methodology/capabilitypatterns/Economic metrics_47095A4C.html"];
contentPage.processPage.elementUrls["_9eLYIPXgEeK5hM6umiquuA"] = ["Legacy application PSMs","ARTIST Methodology/capabilitypatterns/Legacy application PSMs_68E80D08.html"];
contentPage.processPage.elementUrls["_guzjgvU5EeKQUIzBL7h9Mw"] = ["Optimize Application Feature","ARTIST Methodology/capabilitypatterns/Optimize Application Feature_1FFE1234.html"];
contentPage.processPage.elementUrls["_YZkFoBjBEeOB0MMwY_jmZw"] = ["(Redefined) provider management process","ARTIST Methodology/capabilitypatterns/Redefined provider management process_F6927546.html"];
contentPage.processPage.elementUrls["_rOyIoBlEEeOYd55vlpVPlw"] = ["Key resources identified","ARTIST Methodology/capabilitypatterns/Key resources identified_BBFA4DDD.html"];
contentPage.processPage.elementUrls["_gwM7UPXhEeK5hM6umiquuA"] = ["Certification label (Gold, silver, bronze)","ARTIST Methodology/capabilitypatterns/Certification label_9F63B71E.html"];
contentPage.processPage.elementUrls["_3XmvUBi6EeOB0MMwY_jmZw"] = ["Development Processes","ARTIST Methodology/capabilitypatterns/Development Processes_36110787.html"];
contentPage.processPage.elementUrls["_HoxgsPXdEeK5hM6umiquuA"] = ["Low-level models","ARTIST Methodology/capabilitypatterns/Low-level models_A369E98.html"];
contentPage.processPage.elementUrls["_b8YDoBlGEeOYd55vlpVPlw"] = ["Cost structure defined","ARTIST Methodology/capabilitypatterns/Cost structure defined_ED08B533.html"];
contentPage.processPage.elementUrls["_ct5uEPXiEeK5hM6umiquuA"] = ["Artifact Engineer","ARTIST Methodology/capabilitypatterns/Artifact Engineer_8856C846.html"];
contentPage.processPage.elementUrls["_IqT8oPUhEeKQUIzBL7h9Mw"] = ["Migration","ARTIST Methodology/capabilitypatterns/Migration_AEAFBB87.html"];
contentPage.processPage.elementUrls["_bQBf8BjCEeOB0MMwY_jmZw"] = ["Market Segment","ARTIST Methodology/capabilitypatterns/Market Segment_FACA1BD5.html"];
contentPage.processPage.elementUrls["_5zi2gPU9EeKQUIzBL7h9Mw"] = ["Verification of the Behavioral Equivalence with test cases","ARTIST Methodology/capabilitypatterns/Verification of the Behavioral Equivalence with test cases_280E8102.html"];
contentPage.processPage.elementUrls["_r61vIPXeEeK5hM6umiquuA"] = ["Metamodel","ARTIST Methodology/capabilitypatterns/Metamodel_371E2A16.html"];
contentPage.processPage.elementUrls["_8kwV8BlEEeOYd55vlpVPlw"] = ["Cost structure","ARTIST Methodology/capabilitypatterns/Cost structure_9749559.html"];
contentPage.processPage.elementUrls["_z6z9APVHEeKQUIzBL7h9Mw"] = ["Certification of the migrated product","ARTIST Methodology/capabilitypatterns/Certification of the migrated product_AA60743.html"];
contentPage.processPage.elementUrls["_FQO8APXdEeK5hM6umiquuA"] = ["Taxonomy of legacy artefacts","ARTIST Methodology/capabilitypatterns/Taxonomy of legacy artefacts_438CF288.html"];
contentPage.processPage.elementUrls["_-MXCYBlDEeOYd55vlpVPlw"] = ["Study of the current relationship with the customers","ARTIST Methodology/capabilitypatterns/Study of the current relationship with the customers_747D5050.html"];
contentPage.processPage.elementUrls["_PoKkoBjFEeOB0MMwY_jmZw"] = ["Sales numbers","ARTIST Methodology/capabilitypatterns/Sales numbers_713E074D.html"];
contentPage.processPage.elementUrls["_iQGW4PXYEeK5hM6umiquuA"] = ["Processes affected migration","ARTIST Methodology/capabilitypatterns/Processes affected migration_7A928D4E.html"];
contentPage.processPage.elementUrls["_c5PtUPXgEeK5hM6umiquuA"] = ["Tester","ARTIST Methodology/capabilitypatterns/Tester_A480E539.html"];
contentPage.processPage.elementUrls["_bMHpYxbrEeOcBIah627ajg"] = ["Current organization chart","ARTIST Methodology/capabilitypatterns/Current organization chart_DF97DCE6.html"];
contentPage.processPage.elementUrls["_TUvkEBjFEeOB0MMwY_jmZw"] = ["Sales strategy and communication channels redefined","ARTIST Methodology/capabilitypatterns/Sales strategy and communication channels redefined_EC0BEB8E.html"];
contentPage.processPage.elementUrls["_WZbWcRbrEeOcBIah627ajg"] = ["Current accountability process","ARTIST Methodology/capabilitypatterns/Current accountability process_E0E56A7B.html"];
contentPage.processPage.elementUrls["_onbg0PXiEeK5hM6umiquuA"] = ["Initial set of changes to be made to the artefact","ARTIST Methodology/capabilitypatterns/Initial set of changes to be made to the artefact_E32F904E.html"];
contentPage.processPage.elementUrls["_MD_1QfUhEeKQUIzBL7h9Mw"] = ["Migration Artefact Reuse and Evolution","ARTIST Methodology/capabilitypatterns/Migration Artefact Reuse and Evolution_CBAF9C98.html"];
contentPage.processPage.elementUrls["_bMHpZBbrEeOcBIah627ajg"] = ["Renewed organization chart","ARTIST Methodology/capabilitypatterns/Renewed organization chart_A054EACF.html"];
contentPage.processPage.elementUrls["_pFEqIBlEEeOYd55vlpVPlw"] = ["Involved personnel identified","ARTIST Methodology/capabilitypatterns/Involved personnel identified_25A66158.html"];
contentPage.processPage.elementUrls["_z2j9oPXgEeK5hM6umiquuA"] = ["Legacy application source code","ARTIST Methodology/capabilitypatterns/Legacy application source code_ABB5FE50.html"];
contentPage.processPage.elementUrls["_bHY6oBi9EeOB0MMwY_jmZw"] = ["Incidence Management Process","ARTIST Methodology/capabilitypatterns/Incidence Management Process_A034F8E5.html"];
contentPage.processPage.elementUrls["_Abi9ovXgEeK5hM6umiquuA"] = ["Target Cloud PDMs","ARTIST Methodology/capabilitypatterns/Target Cloud PDMs_263296E0.html"];
contentPage.processPage.elementUrls["_PIthMPXWEeK5hM6umiquuA"] = ["Target Platform specification","ARTIST Methodology/capabilitypatterns/Target Platform specification_D10714C8.html"];
contentPage.processPage.elementUrls["_n-YB4BjCEeOB0MMwY_jmZw"] = ["Current customer profile","ARTIST Methodology/capabilitypatterns/Current customer profile_54D9500E.html"];
contentPage.processPage.elementUrls["_2-UlQBi9EeOB0MMwY_jmZw"] = ["Current SLA Management process","ARTIST Methodology/capabilitypatterns/Current SLA Management process_CD50DC12.html"];
contentPage.processPage.elementUrls["_V-Vj4RjCEeOB0MMwY_jmZw"] = ["Business Model Related Tasks","ARTIST Methodology/capabilitypatterns/Business Model Related Tasks_2EA77441.html"];
contentPage.processPage.elementUrls["_Abi9oPXgEeK5hM6umiquuA"] = ["M2T code generation patterns (transformations)","ARTIST Methodology/capabilitypatterns/M2T code generation patterns transformations_2CFBA2BA.html"];
contentPage.processPage.elementUrls["_fQ2zAPXiEeK5hM6umiquuA"] = ["Change or Modification Request","ARTIST Methodology/capabilitypatterns/Change or Modification Request_9E2544AC.html"];
contentPage.processPage.elementUrls["_RihFoPXgEeK5hM6umiquuA"] = ["Migrated application deployment unit","ARTIST Methodology/capabilitypatterns/Migrated application deployment unit_FE10DE3E.html"];
