/*
* generated by Xtext
*/
package eu.artist.postmigration.nfrvt.lang.gml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GMLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("eu/artist/postmigration/nfrvt/lang/gml/parser/antlr/internal/InternalGML.tokens");
	}
}
