
package rule_api_test

import eu.artist.methodology.mpt.model.MigrationGoals;
import eu.artist.methodology.mpt.model.TechnicalGoals;

global eu.artist.methodology.mpt.model.Result result;
global eu.artist.methodology.mpt.model.TestVariable testVariable;
global eu.artist.methodology.mpt.cheatsheet.rules.RulesVariable rulesVariable;
//declare any global variables here

rule "Rule_1"

	when 
		MigrationGoals (technicalGoals.a_p.databaseScalabilityRequirements == "high_scalability" && technicalGoals.iaas.targetPlatform == "AEC2")
	then 
		System.out.println("Matched Rule One"); 
		System.out.println("Do something with EMREQ and OPTAPPFEA");
		
		result.setStringResult("Do something with EMREQ and OPTAPPFEA");
		result.setIntegerResult(new Integer(5));
		result.setBooleanResult(true);
		
		rulesVariable.addInArray("RULE_1_RETURNS_TRUE");
		//testVariable.setTestString("RULE_1_RETURNS_TRUE");

end

rule "Rule_2"

	when 
		MigrationGoals (businessGoals.bil.getRule() == "use")
	then 
		System.out.println("Matched Rule Two"); 
		System.out.println("Do something with REVE, EMREQ and OPTAPPFEA");
		
		result.setStringResult("Do something with REVE, EMREQ and OPTAPPFEA");
		result.setIntegerResult(new Integer(5));
		result.setBooleanResult(true);
		
		rulesVariable.addInArray("RULE_2_RETURNS_TRUE");
		
		//testVariable.setTestString("RULE_2_RETURNS_TRUE");

end

