/*******************************************************************************
 * Copyright (c) 2014 Atos.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * 	Burak Karaboga (Atos) - initial API and implementation
 * 	Initially developed in the context of ARTIST EU project www.artist-project.eu
 *******************************************************************************/
package rule_api_test

import eu.artist.methodology.mpt.model.MigrationGoals;
import eu.artist.methodology.mpt.model.TechnicalGoals;

global eu.artist.methodology.mpt.model.Result result;
global eu.artist.methodology.mpt.model.TestVariable testVariable;
global eu.artist.methodology.mpt.cheatsheet.rules.RulesVariable rulesVariable;
//declare any global variables here

rule "Rule_1"

	when 
		MigrationGoals (technicalGoals.a_p.databaseScalabilityRequirements == "high_scalability" && technicalGoals.iaas.targetPlatform == "AEC2")
	then 
		System.out.println("Matched Rule One"); 
		System.out.println("Do something with EMREQ and OPTAPPFEA");
		
		result.setStringResult("Do something with EMREQ and OPTAPPFEA");
		result.setIntegerResult(new Integer(5));
		result.setBooleanResult(true);
		
		rulesVariable.addInArray("RULE_1_RETURNS_TRUE");
		//testVariable.setTestString("RULE_1_RETURNS_TRUE");

end

rule "Rule_2"

	when 
		MigrationGoals (businessGoals.bil.getRule() == "use")
	then 
		System.out.println("Matched Rule Two"); 
		System.out.println("Do something with REVE, EMREQ and OPTAPPFEA");
		
		result.setStringResult("Do something with REVE, EMREQ and OPTAPPFEA");
		result.setIntegerResult(new Integer(5));
		result.setBooleanResult(true);
		
		rulesVariable.addInArray("RULE_2_RETURNS_TRUE");
		
		//testVariable.setTestString("RULE_2_RETURNS_TRUE");

end

rule "Rule_3"

	when 
		MigrationGoals (technicalGoals.iaas.targetPlatform == "Azure")
	then 
		System.out.println("Matched Rule Three"); 
		System.out.println("Skip Target Environment Specification tasks.");
		
		result.setStringResult("Skip Target Environment Specification tasks.");
		result.setIntegerResult(new Integer(5));
		result.setBooleanResult(true);
		
		rulesVariable.addInArray("RULE_3_RETURNS_TRUE");
		
		//testVariable.setTestString("RULE_2_RETURNS_TRUE");

end

