/*
* generated by Xtext
*/
package eu.artist.migration.mdt.database.sql.editor;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SQLDSLStandaloneSetup extends SQLDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new SQLDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

