<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="movies" nsURI="http://www.eclipse.org/henshin/examples/movies/1.0"
    nsPrefix="movies">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Movie" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="playBack" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/playsIn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="playsIn" upperBound="-1"
        eType="#//Movie" eOpposite="#//Movie/playBack"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actress" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Couple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="p1" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p2" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occursIn" eType="#//Movie"/>
  </eClassifiers>
</ecore:EPackage>
