/**
 * generated by Xtext
 */
package eu.artist.postmigration.nfrvt.lang.nsl.scoping;

import eu.artist.postmigration.nfrvt.lang.common.scoping.ARTISTCommonScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class NSLScopeProvider extends ARTISTCommonScopeProvider {
}
