/*
* generated by Xtext
*/
package eu.artist.postmigration.nfrvt.lang.common.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ARTISTCommonAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("eu/artist/postmigration/nfrvt/lang/common/parser/antlr/internal/InternalARTISTCommon.tokens");
	}
}
