/*
 * generated by Xtext
 */
package eu.artist.postmigration.nfrvt.lang.nsl.ui.contentassist

import eu.artist.postmigration.nfrvt.lang.nsl.ui.contentassist.AbstractNSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class NSLProposalProvider extends AbstractNSLProposalProvider {
}
