/*
 * generated by Xtext
 */
package eu.artist.postmigration.nfrvt.lang.pml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import eu.artist.postmigration.nfrvt.lang.pml.ui.internal.PMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PMLActivator.getInstance().getInjector(PMLActivator.EU_ARTIST_POSTMIGRATION_NFRVT_LANG_PML_PML);
	}
	
}
